version: '3'
services:
  client:
    build: ./client
    volumes:
      - ./client/data:/data
    depends_on:
      - server

  server:
    build: ./server
    volumes:
      - ./server/data:/app/data
    ports:
      - "8080:8080"
